### ISSUE TITLE
Breaking Error when starting to type inside the editor. Cannot update a component (`HotReload`) while rendering a different component (`qr`)

### ISSUE THREAD

**Issue by vincenzodomina** [TypeCellOS/BlockNote#1166]
**Describe the bug**
Breaking Error when starting to type inside the editor. It immediately focuses away after the first letter and when I open the block menu and click on any item it errors: 

app-index.tsx:25 Warning: Cannot update a component (`HotReload`) while rendering a different component (`qr`). To locate the bad setState() call inside `qr`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render Error Component Stack
    at qr (blocknote-react.js:2401:1)
    at div (<anonymous>)
    at Xr (blocknote-react.js:2479:1)
    at si (blocknote-react.js:2831:1)
    at div (<anonymous>)
    at fi (blocknote-react.js:2888:19)
    at mi (blocknote-react.js:2929:1)
    at MantineThemeProvider (MantineThemeProvider.tsx:18:3)
    at MantineProvider (MantineProvider.tsx:14:3)
    at on (blocknote-mantine.js:1635:11)
    at div (<anonymous>)

![image](https://github.com/user-attachments/assets/a41d8f8f-1f8e-4193-8712-a6d24fc4a6cb)

I had v.015.11 running with this issue, upgraded to 0.17.0 and still existing issue.

EDIT:
There are more errors following the above error, might be a cascading effect but maybe helps:
![image](https://github.com/user-attachments/assets/0113f61b-4ae7-4f0a-8e75-4dc22d9228c2)

Here is the script within blocknote/core where this is coming from
![image](https://github.com/user-attachments/assets/e8120246-1cb6-47e6-886c-b2e0da950065)
I added the conditional chaining which lets the error disappear, but the focusing away problem persists

**To Reproduce**
- Open editor in the app, either blank or prefilled
- Start typing, first letter appears but it focuses away on its own
- Then when starting a command and clicking on any item in the menu list, the app breaks and the above errors appear
- The same error when clicking any item in the context menu from the block plus sign

**Misc**
"@blocknote/core": "^0.17.0",
"@blocknote/mantine": "^0.17.0",
"@blocknote/react": "^0.17.0",
Node version: 20.12.2
Package manager: npm
Browser: Chrome latest
React: Nextjs 14.1.4 App router

**Comment by vincenzodomina** [comment]
I created a minimal example with my next.js setup and so far it works:
https://stackblitz.com/edit/github-m4y9eq?file=components%2FApp.tsx

Will dig deeper and report.
