### ISSUE TITLE
Using ServerBlockNoteEditor.create() in next.js accesses createContext

### ISSUE THREAD

**Issue by quiqueck** [TypeCellOS/BlockNote#1189]
**Describe the bug**
Calling ServerBlockNoteEditor.create() on a server route in next.js 14 app-router causes an error:
```
⨯ createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(rsc)/./node_modules/@floating-ui/react/dist/floating-ui.react.mjs:402:77)
    at (rsc)/./node_modules/@floating-ui/react/dist/floating-ui.react.mjs (./.next/server/vendor-chunks/@floating-ui.js:100:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@blocknote/react/dist/blocknote-react.js:106:76)
    at (rsc)/./node_modules/@blocknote/react/dist/blocknote-react.js (./.next/server/vendor-chunks/@blocknote.js:30:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@blocknote/server-util/dist/blocknote-server-util.js:6:74)
    at (rsc)/./node_modules/@blocknote/server-util/dist/blocknote-server-util.js (./.next/server/vendor-chunks/@blocknote.js:40:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/api/worlds/byid/[wid]/topics/[tid]/route.ts:5:80)
    at (rsc)/./app/api/worlds/byid/[wid]/topics/[tid]/route.ts (./.next/server/app/api/worlds/byid/[wid]/topics/[tid]/route.js:142:1)
    at __webpack_require__ (./.next/server/webpack-runtime.js:33:43)    
```

**To Reproduce**
This is the `route.ts`-file I created.
```
import { ServerBlockNoteEditor } from '@blocknote/server-util'
import { NextResponse } from 'next/server'
interface Params {
  wid: string
  tid: string
}
export async function GET(
  request: Request,
  { params: { wid, tid } }: { params: Params }
) {
  const editor = ServerBlockNoteEditor.create({})

  return NextResponse.json({ text: 'Hello World' })
}
```
**Misc**
- "next": "14.2.15"
- "@blocknote/core": "^0.17.1",
- "@blocknote/mantine": "^0.17.1",
- "@blocknote/react": "^0.17.1",
- "@blocknote/server-util": "^0.17.1",
- "@blocknote/shadcn": "^0.17.1",
- npm
- Browser: curl
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by Ikram-Maulana** [comment]
I'm experiencing the same thing in Blocknote version 18.0.1, is there a recent update regarding this?

**Comment by YousefED** [comment]
see here: https://github.com/TypeCellOS/BlockNote/issues/942#issuecomment-2275681704

**Comment by curiousyuvi** [comment]
I found a solution for this, see: [#942 (comment)](https://github.com/TypeCellOS/BlockNote/issues/942#issuecomment-2570750560)
