### ISSUE TITLE
Error getting blocks from valid  yXml fragment

### ISSUE THREAD

**Issue by deanthing** [TypeCellOS/BlockNote#1339]
**Describe the bug**
Fail to get blocks even though yXml fragment contains valid blocks.

**To Reproduce**
Use `ServerBlockNoteEditor` to extract blocks from yXml fragment. Validate that yXml json representation is correct.
```
const yBinaryUpdate = await liveblocks.getYjsDocumentAsBinaryUpdate(noteId);
const yDoc = new Y.Doc();
Y.applyUpdate(yDoc, new Uint8Array(yBinaryUpdate));
const fragment = yDoc.getXmlFragment("document-store")
console.log(rags.toJSON())
// output: <blockgroup><blockcontainer backgroundColor="default" id="d6e45a81-abd7-4a90-8ef4-9919897dce16" textColor="gray"><heading level="1" textAlignment="left">Doc title</heading></blockcontainer><blockcontainer backgroundColor="default" id="5773b166-20f5-4a7f-aff6-34ebc1b861e9" textColor="default"><paragraph textAlignment="left">doc paragpraph</paragraph></blockcontainer><blockcontainer backgroundColor="default" id="f2eab2be-15f1-403e-9965-b0ac43a6cf3c" textColor="default"><paragraph textAlignment="left"></paragraph></blockcontainer></blockgroup>


const editor = ServerBlockNoteEditor.create();
const blocks = editor.yXmlFragmentToBlocks(frags)

Error in processNote: TypeError: text.toDelta is not a function
    at createTextNodesFromYText (.../y-prosemirror/src/plugins/sync-plugin.js:758:23)
    at createChildren (.../y-prosemirror/src/plugins/sync-plugin.js:690:18)
    at Array.forEach (<anonymous>)
    at createNodeFromYElement (.../y-prosemirror/src/plugins/sync-plugin.js:708:18)
    at .../y-prosemirror/src/lib.js:202:5
    at Array.map (<anonymous>)
    at yXmlFragmentToProseMirrorFragment (.../y-prosemirror/src/lib.js:201:50)
    at yXmlFragmentToProseMirrorRootNode (.../y-prosemirror/src/lib.js:218:35)
    at aT.yXmlFragmentToBlocks (.../blocknote-server-util.js:20642:15)
    at Module.processNote(.../src/services/noteService.mjs:12:31)
```

**Misc**
-  "@blocknote/server-util": "^0.21.0",
- Node version: node:18.7.0-alpine
- Package manager: npm

**Comment by deanthing** [comment]
Solved by not mixing ESM and CJS imports.
