### ISSUE TITLE
React does not recognize the `isSelected` prop on a DOM element

### ISSUE THREAD

**Issue by iboughtbed** [TypeCellOS/BlockNote#246]
**Code**

```  
const editor: BlockNoteEditor | null = useBlockNote({
    theme: "light",
});

return (
    <>
        <BlockNoteView editor={editor} />
    </>
)
```

**What's wrong**

When I select text it logs an error in console: 

`client.js:1 Warning: React does not recognize the 'isSelected' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'isselected' instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Box/Box.js:45:18)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/UnstyledButton/UnstyledButton.js:47:87)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Button/Button.js:57:87)
    at eval (webpack-internal:///./node_modules/@blocknote/react/dist/blocknote-react.js:1523:17)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Popover/PopoverTarget/PopoverTarget.js:55:87)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Menu/MenuTarget/MenuTarget.js:51:87)
    at Provider (webpack-internal:///./node_modules/@mantine/core/node_modules/@mantine/utils/esm/create-safe-context/create-safe-context.js:18:23)
    at Popover (webpack-internal:///./node_modules/@mantine/core/esm/Popover/Popover.js:62:65)
    at Provider (webpack-internal:///./node_modules/@mantine/core/node_modules/@mantine/utils/esm/create-safe-context/create-safe-context.js:18:23)
    at Menu (webpack-internal:///./node_modules/@mantine/core/esm/Menu/Menu.js:72:87)
    at sv (webpack-internal:///./node_modules/@blocknote/react/dist/blocknote-react.js:1539:15)
    at gv (webpack-internal:///./node_modules/@blocknote/react/dist/blocknote-react.js:1554:7)
    at div
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Box/Box.js:45:18)
    at eval (webpack-internal:///./node_modules/@mantine/core/esm/Group/Group.js:50:87)
    at Gl (webpack-internal:///./node_modules/@blocknote/react/dist/blocknote-react.js:1100:99)
    at vv (webpack-internal:///./node_modules/@blocknote/react/dist/blocknote-react.js:1618:37)
    at Tippy (webpack-internal:///./node_modules/@tippyjs/react/dist/tippy-react.esm.js:168:25)
    at TippyWrapper (webpack-internal:///./node_modules/@tippyjs/react/dist/tippy-react.esm.js:517:25)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:123:50)
    at MantineProvider (webpack-internal:///./node_modules/@mantine/styles/esm/theme/MantineProvider.js:76:3)
    at Bl (webpack-internal:///./node_modules/@blocknote/react/dist/blocknote-react.js:745:15)`

**To Reproduce**

In editor, select any text (using arrow keys, mouse), it logs an error in console.

 

**Misc**
- Node version: v18.16.0
- Package manager: npm
- Browser:  Chrome v114.0.5735.134 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by tsl1127** [comment]
the same problem

**Comment by YousefED** [comment]
Thanks! will be fixed here: https://github.com/TypeCellOS/BlockNote/pull/253
