### ISSUE TITLE
Image Block not working

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#393]
I am getting below error while adding image block using slash menu. How can I fix that?
Uncaught TypeError: Cannot read properties of undefined (reading 'left')
    at getBoundingClientRect (getBoundingClientRect.js:27:1)
    at getCompositeRect (getCompositeRect.js:27:35)
    at Object.forceUpdate (createPopper.js:96:38)
    at tippy-react.esm.js:293:1
    at commitHookEffectListMount (react-dom.development.js:23160:28)
    at commitLayoutEffectOnFiber (react-dom.development.js:23283:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24698:11)
    at commitLayoutEffects_begin (react-dom.development.js:24684:9)
    at commitLayoutEffects (react-dom.development.js:24622:5)
    at commitRootImpl (react-dom.development.js:26833:7)
    at commitRoot (react-dom.development.js:26692:7)
    at performSyncWorkOnRoot (react-dom.development.js:26127:5)
    at flushSyncCallbacks (react-dom.development.js:12052:24)
    at flushSyncCallbacksOnlyInLegacyMode (react-dom.development.js:12031:7)
    at scheduleUpdateOnFiber (react-dom.development.js:25551:9)
    at dispatchSetState (react-dom.development.js:17537:9)

**Comment by matthewlipski** [comment]
Hi, do you have the steps to reproduce this error?
